name: flask-api-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - flask==3.0.0
    - flask-sqlalchemy==3.1.1
    - flask-migrate==4.0.5
    - psycopg2-binary==2.9.9
    - pymysql==1.1.0
    - redis==5.0.1
    - python-dotenv==1.0.0
    - marshmallow==3.20.1
    - flask-cors==4.0.0
    - gunicorn==21.2.0
